### ISSUE TITLE
Fishshell incompatible

### ISSUE THREAD

**Issue by territory-sschneider** [srevinsaju/zap#10]
Seems like the tool does not play well with fishshell.
```
> curl -fsSL https://git.io/zapinit | sh
Creating ~/.zap
 Downloading the latest 🗲 Zap Release
~. 100%[=============>]  22,28M  2,61MB/s    in 18s
Adding zap to PATH
 🗲 Zap  is installed

  • Join our chat on  Discord : https://discord.gg/Yv7KC68
  • Found an issue? Report it now on  GitHub  @ https://github.com/srevinsaju/zap/issues
  • Have questions? Hope on to  #Appimage  on IRC freenode
  .net

Try it now by running  zap  on your terminal
Have fun!
> zap
Failed to execute process '~/.local/bin/zap'. Reason:
exec: Exec format error
The file '~/.local/bin/zap' is marked as an executable but could not be run by the operating system.
```

**Comment by srevinsaju** [comment]
Interesting. Which OS are you running and what is the architecture?

**Comment by territory-sschneider** [comment]
![image](https://user-images.githubusercontent.com/73951566/101875952-d7167c00-3b8b-11eb-9386-af8629845001.png)

**Comment by territory-sschneider** [comment]
![image](https://user-images.githubusercontent.com/73951566/101877594-86ece900-3b8e-11eb-9ac4-4034bcc4657f.png)

**Comment by srevinsaju** [comment]
Thanks for the information.

What about
```bash
~/.zap/zap-x86_64.AppImage --help
```

**Comment by territory-sschneider** [comment]
![image](https://user-images.githubusercontent.com/73951566/101878308-9f113800-3b8f-11eb-89ab-4845e84959df.png)

**Comment by srevinsaju** [comment]
Ok, 
```bash
which zap
zap --help
cat `which zap`
```

**Comment by territory-sschneider** [comment]
![image](https://user-images.githubusercontent.com/73951566/101878593-2068ca80-3b90-11eb-8b90-dd4304f8a4fb.png)

**Comment by territory-sschneider** [comment]
Missing a shebang maybe?

**Comment by srevinsaju** [comment]
Ah got the error. My bad...

Add this `#!/bin/bash` to that file 
```
#!/bin/bash
/home/sc..
```

**Comment by srevinsaju** [comment]
> Missing a shebang maybe?

yup, need to fix that. Thanks for finding and helping debug :smile:

**Comment by territory-sschneider** [comment]
appreciated. that fixed it.

**Comment by territory-sschneider** [comment]
So I can finally dip my toes into the AppImage business easily

**Comment by srevinsaju** [comment]
> So I can finally dip my toes into the AppImage business easily

:smile: Thanks for reporting!!

**Comment by srevinsaju** [comment]
> one more thing
> ![image](https://user-images.githubusercontent.com/73951566/101879138-2317ef80-3b91-11eb-8cd6-c7f84c495553.png)

just add that to your `~/.fishrc` and you are done. Make sure you open a new terminal before running `zap` again :)

**Comment by srevinsaju** [comment]
Looks like `fish` does not have a `fishrc`, it maybe `~/.config/fish/config.fish`

**Comment by territory-sschneider** [comment]
point is, fish doesn't work that way :) fish uses set and not export
```
set -x ZAP_PATH ~/.local/share/zap/bin
set --universal fish_user_paths $ZAP_PATH $fish_user_paths 
```

**Comment by srevinsaju** [comment]
oh, I see. I have never used `fish`. I will add a fix that would detect fish shell and add this as what you have said. Does adding this make `zap` work properly?

**Comment by territory-sschneider** [comment]
it does

**Comment by srevinsaju** [comment]
Perfect. Thanks :smile:
