### ISSUE TITLE
Zap Fails to Install qBittorrent

### ISSUE THREAD

**Issue by kj4ezj** [srevinsaju/zap#101]
I don't know how to determine if an `*.AppImage` is formatted correctly, so please point me in the right direction if qBittorrent is packaging their `*.AppImage` incorrectly so I can file a useful issue there.

When I try to install [qBittorrent](https://www.qbittorrent.org) with the following `zap` command, it fails to install.
```bash
zap install qbittorrent ~/Downloads/qbittorrent-4.4.5_x86_64.AppImage
```
Here is a screenshot.

![2022-10-30 12-24-58 - zap qbittorrent](https://user-images.githubusercontent.com/34947245/199070334-8153ccfa-19e1-4f4f-b51a-a5dd8f44558f.png)

There is nothing on the start menu or desktop after this. There is also no folder in `~/.local/share/zap/v2/` corresponding to qBittorrent, nor any symbolic link in `~/.local/bin/`. Strangely, the correct icon does exist at `~/.local/share/zap/v2/icons/qbittorrent.png`. I verified this by opening it in an image viewer.

System
```
Kernel: 5.4.0-131-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
base: Ubuntu 20.04 focal
```
Zap
```
Zap version Build:v2.2.1.6.gdc5b7ff 1646814234
```

**Comment by srevinsaju** [comment]
Hmm, looks like the image is corrupted on qbittorrent for some reason :thinking: I will need to debug whats happening behind.

**Comment by srevinsaju** [comment]
@kj4ezj thanks for the issue. Looks like `zap` did not recognize SVG images, and hence it stopped. I have added a patch. Please update to the latest version of zap once the builds complete on main branch

**Comment by kj4ezj** [comment]
I have confirmed this is working now!

![2022-11-30 14-35-46 - qBittorrent zap installation worked](https://user-images.githubusercontent.com/34947245/204894329-3562490f-ee26-4684-a595-3e87c720e12a.png)

The icon is also not missing with system integration using your `*.svg` fix, as described in [issue 92](https://github.com/srevinsaju/zap/issues/92) for other `*.AppImage` files.

![2022-11-30 14-42-29 - qBittorrent system integration working](https://user-images.githubusercontent.com/34947245/204894678-490b31bd-6e3f-4534-9404-0967584d3b22.png)

Thank you so much @srevinsaju! I would appreciate if you are able to link your pull request to this issue or in a comment so I can see the changes you made and potentially contribute in the future.
