### ISSUE TITLE
The app does not provide any releases.

### ISSUE THREAD

**Issue by territory-sschneider** [srevinsaju/zap#12]
isn't it actually this then?  `no valid OpenPGP data found` 
`zap install enpass`
![image](https://user-images.githubusercontent.com/73951566/101905113-36d64c80-3bb7-11eb-8f96-42f31931e146.png)

https://appimage.github.io/Enpass/

**Comment by srevinsaju** [comment]
I apologize, I missed this issue.

Interesting. I found the error. Will fix in a while

**Comment by srevinsaju** [comment]
@territory-sschneider zap v2 based on `golang` is now available in beta, you might like to check it out 

https://github.com/srevinsaju/zap/releases/tag/v2-continuous
