### ISSUE TITLE
Minor bug & Feature Request

### ISSUE THREAD

**Issue by gr523** [srevinsaju/zap#16]
**I  gotta say it really is a delightful application**

First of all I would like to address a bug
after `zap remove package` the symlink in ~/.local/bin is not deleted.As a result,when the application is installed again the symlink is not placed,outputing `[ FATAL ] ...... symlink dir/X.AppImage ~/.local/bin/X exists` and so the application doesn't open
steps to produce:
`zap install qpdf` install the latest
`zap remove qpdf`
`zap install qpdf` install anything except the latest ( it just has to be different version  each time)
I have also noticed that this error doesn't occur when the appimage name is not suffixed by its version,for example neovim gets installed as nvim.appimage no matter what version and this error doesn't occur

EDIT : Installing appimages from local file works :)
`zap install --from file://X nameOfApp`

Updating apps installed by `zap install --github --from x/Y`
I get that I can update those by running the same command again,but for that I would have to look up the repo location again.
An easy fix would be to save the location of Y as github.com/x/Y so when I want to install/update it again I can just run
`zap install Y` 
but of course if the appimage contains zsync for update it isn't required,but at this moment most appimages doesnt have that

On a side note,libappimage should be listed as a dependency

**Comment by srevinsaju** [comment]
> **I gotta say it really is a delightful application**

Thanks ✨

> 
> First of all I would like to address a bug
> after `zap remove package` the symlink in ~/.local/bin is not deleted.As a result,when the application is installed again the symlink is not placed,outputing `[ FATAL ] ...... symlink dir/X.AppImage ~/.local/bin/X exists` and so the application doesn't open
> steps to produce:
> `zap install qpdf` install the latest
> `zap remove qpdf`
> `zap install qpdf` install anything except the latest ( it just has to be different version each time)
> I have also noticed that this error doesn't occur when the appimage name is not suffixed by its version,for example neovim gets installed as nvim.appimage no matter what version and this error doesn't occur
> 

Agreed, this has had been a bug, possibly fixed in https://github.com/srevinsaju/zap/commit/d0f4bc88016671e0ad88d1b6c2db085d618d557e, which I forgot to push (my bad)


> EDIT : Installing appimages from local file works :)
> `zap install --from file://X nameOfApp`
> 

:smile: 


> Updating apps installed by `zap install --github --from x/Y`
> I get that I can update those by running the same command again,but for that I would have to look up the repo location again.
> An easy fix would be to save the location of Y as github.com/x/Y so when I want to install/update it again I can just run
> `zap install Y`
> but of course if the appimage contains zsync for update it isn't required,but at this moment most appimages doesnt have that
> 

Ah yes, I agree. That would be a good feature. I will try to get this working as soon as possible.

> On a side note,libappimage should be listed as a dependency

`libappimage` is not a dependency. Most of `libappimage` has been rewritten in golang. `libappimage` was a dependency in its v1, i.e python version. `zap` then got re written in golang, which removed the need for this dependency. Are you sure you required `libappimage` to use `zap`?

**Comment by gr523** [comment]
>Agreed, this has had been a bug, possibly fixed in d0f4bc8, which I forgot to push (my bad)

Great

> libappimage is not a dependency. Most of libappimage has been rewritten in golang. libappimage was a dependency in its v1, i.e python version. zap then got re written in golang, which removed the need for this dependency. Are you sure you required libappimage to use zap?

I was talking about running appimages,zap will run fine but not the appimages.So it kinda make sense to be a requirement.

On another thought,It would be great if the user had the option not to create the symlink in ~/.local/bin because we might want to run different version of the same application or maybe already have a normal installation of the same app.In my case I just remove all these from ~/.local/bin because I dont wanna flood it by something I will never use or maybe I'm the only one thinking this. whats your thought in this

zap has so much potential,I'm really looking forward to its development. Thanks for this awesome project

**Comment by srevinsaju** [comment]
> > Agreed, this has had been a bug, possibly fixed in [d0f4bc8](https://github.com/srevinsaju/zap/commit/d0f4bc88016671e0ad88d1b6c2db085d618d557e), which I forgot to push (my bad)
> 
> Great
> 
> > libappimage is not a dependency. Most of libappimage has been rewritten in golang. libappimage was a dependency in its v1, i.e python version. zap then got re written in golang, which removed the need for this dependency. Are you sure you required libappimage to use zap?
> 
> I was talking about running appimages,zap will run fine but not the appimages.So it kinda make sense to be a requirement.

AppImage's don't require `libappimage` to run. AppImage has the principle of one app = one file, and being standalone. Perhaps, its just a particular appimage which requires `libappimag`, it should be reported to the app developer to bundle `libappimage` alone. I am not aware of any apps which require the same. Can you give some examples?


> 
> On another thought,It would be great if the user had the option not to create the symlink in ~/.local/bin because we might want to run different version of the same application or maybe already have a normal installation of the same app.In my case I just remove all these from ~/.local/bin because I dont wanna flood it by something I will never use or maybe I'm the only one thinking this. whats your thought in this

Agreed. I can add a configuration option for that. Thanks for the idea.

> 
> zap has so much potential,I'm really looking forward to its development. Thanks for this awesome project

**Comment by gr523** [comment]
You are right,it seems like I was missing something else when I thought it was libappimage

Another reminder,
The symlink problem is more problematic than I thought,upon symlink creation it is not forced,if file exists it doesn't link so an update never actually points to the updated file because the desktop files are using the symlink on Exec,I think its better to use the full path to Exec and take symlinks out of the equation as its causing more problem then convenience
I also faced another error while installing some apps,but i am not sure what could be the reason
```
[WARN]  2021/04/23 23:58:25 Reading desktop file failed open /tmp/zap843445265/squashfs-root/nvim.desktop: no such file or directory
neovim installed successfully ✨
```
I remember latest neovim ,qbittorrent_enhanced_edition doing this

**Comment by srevinsaju** [comment]
I am addressing this in #3
