### ISSUE TITLE
yet another symlink problem

### ISSUE THREAD

**Issue by gr523** [srevinsaju/zap#19]
`[WARN] .. symlink pathTozapdir/icons/zap-X.png .../icons/hicolor/.../zap-X.png : file exists`

upon inspecting `../icons/hicolor/..zap-X.png` I see that it has created a folder named `zap-X.png` instead of a symlink, which I confirmed did not exist before

**Comment by srevinsaju** [comment]
@gr523 Can you try with the latest release? Might be fixed now

**Comment by gr523** [comment]
just tried with latest,still same issue

also faced 
`[WARN]  2021/06/08 10:51:59 Reading desktop file failed open /tmp/zap179960365/squashfs-root/KittehPlayer.desktop: no such file or directory`
this issue for some appimages also

**Comment by srevinsaju** [comment]
Uff, finally I found a fix to that weird problem. Should be resolved on the latest release which would start building in 5 mins.
Thanks for opening this issue.
