### ISSUE TITLE
Add uname command in the installation instructions

### ISSUE THREAD

**Issue by rodfersou** [srevinsaju/zap#23]
We can use the command `$(uname -m)` to generate the platform:

```bash
% uname -m
arm64
```

```bash
$ uname -m
aarch64
```

**Comment by srevinsaju** [comment]
I wish I could do that, but..

```bash
$ uname -m 
x86_64
```
on my amd64 computer.

unfortunately, go has a completely different architecture specification. I wish we could all come to a conclusion to one single well-define architecture :shrug:. For example `x86_64` is known as `amd64` as well as `x86_64` in different contexts. 

Then in some places, there are `armhf`, `arm` etc.. which are synonymous to what you have shown in the example

**Comment by srevinsaju** [comment]
Closing this, feel free to re-open this if you know of a good solution ✨😄
