### ISSUE TITLE
Install local AppImages

### ISSUE THREAD

**Issue by mirkobrombin** [srevinsaju/zap#24]
I was looking for a method to integrate (install) an AppImage already downloaded on my PC (and which does not offer a direct link to the .AppImage file), I searched in the zap help and in the Readme but I could not find anything about it.

After some tests and resignations I tried to use the `file://` protocol with the `--from` parameter and I saw that it works:
```bash
zap install gravit file:///home/mirko/Downloads/GravitDesigne.AppImage
```
I don't know if this is wanted or not but it could be very useful to have it officially.

**Comment by srevinsaju** [comment]
hey, it's possible to integrate a local appimage using zap. 

this is an example:
```bash
zap install --from file:///home/username/Downloads/myappimage.AppImage gravit-designer
```

Let me know if you face any problems doing the same. I will improve the documentation

**Comment by mirkobrombin** [comment]
> hey, it's possible to integrate a local appimage using zap.
> 
> this is an example:
> 
> ```shell
> zap install --from file:///home/username/Downloads/myappimage.AppImage gravit-designer
> ```
> 
> Let me know if you face any problems doing the same. I will improve the documentation

this is currently what i did but i could not find anything in the help 🤔

**Comment by srevinsaju** [comment]
Ah, thanks for this bug report. I will improve the documentation to reflect the same.

**Comment by srevinsaju** [comment]
@mirkobrombin updated the "installing appimages" documentation, 

https://github.com/srevinsaju/zap/blob/v2/README.md#installing-appimages

Does it look good?

**Comment by mirkobrombin** [comment]
Looks good to me
