### ISSUE TITLE
Update from .appimage file or URL

### ISSUE THREAD

**Issue by goingtosleep** [srevinsaju/zap#27]
There are situations when we don't have a clear github repo (different releases other than appimage) such as `neovim`. 
It would be great if we can 

`zap update nvim --from https://.../nvim.appimage` 

or 

`zap install nvim --from https://.../nvim.appimage --update` 

Now if I want to update an existing app, I have to remove it first, then run the installation again.
Hope this feature will be possible.
Thanks for great app!

**Comment by srevinsaju** [comment]
Ah, that is a good suggestion. Thanks, I will work on it. :rocket:

**Comment by srevinsaju** [comment]
Fixed in #28, new `zap` builds will be available in 10 minutes. Thanks!

**Comment by goingtosleep** [comment]
Ran successfully with 
`zap install --update --from https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage nvim`

Awesome! Thanks a lot!
