### ISSUE TITLE
This app does not provide any candidate for installation

### ISSUE THREAD

**Issue by sheeepdev** [srevinsaju/zap#32]
The title says it.

I'm trying to install glimpse image editor.

**Comment by sheeepdev** [comment]
![image](https://user-images.githubusercontent.com/68562536/128608643-bf553250-7edf-48a6-a487-6c6cb103ee9e.png)

**Comment by srevinsaju** [comment]
use lowercase

**Comment by sheeepdev** [comment]
lmao it was that simple thanks

I just assumed it needed to be uppercase because it said so in search lol

**Comment by srevinsaju** [comment]
It uses the case as specified in this URL: https://g.srev.in/get-appimage/glimpse-image-editor/

**Comment by sheeepdev** [comment]
![image](https://user-images.githubusercontent.com/68562536/128609229-391220f4-7819-4045-b687-0ff5b15279a2.png)

**Comment by sheeepdev** [comment]
I see

**Comment by srevinsaju** [comment]
Where did you get that command from? Can you put the link?

**Comment by sheeepdev** [comment]
What do you mean?
I searched for glimpse (zap search glimpse) and it said to run this to install

**Comment by srevinsaju** [comment]
ah, I see. I completely forgot about the search feature I implemented :facepalm: , thanks for providing me the pointer, it is clearly a bug in `zap`
