### ISSUE TITLE
`zap update` deletes the Appimage image before I choose the update 

### ISSUE THREAD

**Issue by HosamHasanRamadan** [srevinsaju/zap#44]
`zap update 'appimage'` deletes the appimage  before I choose the update or sometimes there is no new update and I will stick with the current version

**Comment by srevinsaju** [comment]
Yes, you are right! It would be really cool if this part could be optimized. I will assign the a "good first issue" and a "hacktoberfest" tag, so that developers can participate in the fix.

**Comment by ratogabriel** [comment]
Please take a look: https://github.com/srevinsaju/zap/pull/48
