### ISSUE TITLE
Automatic Installation failure: Illegal option -o pipefail

### ISSUE THREAD

**Issue by luni3359** [srevinsaju/zap#45]
I tried running the automatic installer but this part here caused it to automatically end:
```bash
set -euo pipefail
```
with error
```
sh: 8: set: Illegal option -o pipefail
```

I couldn't find the root of this issue, however the manual installation worked perfectly.

**Comment by srevinsaju** [comment]
```bash
curl https://raw.githubusercontent.com/srevinsaju/zap/main/install.sh | bash -s
```

Can you check if the above works without errors?

**Comment by luni3359** [comment]
Yes, that helped me get past line 8.

I got an error about not having `jq` installed on my system, but I didn't get anything like that using the manual installation snippet you have on your readme page.

I installed that package and now it's run completely without issues.

**Comment by srevinsaju** [comment]
Thanks for testing, I will update the README with the changes from `sh` to `bash`.

> I got an error about not having jq installed on my system, but I didn't get anything like that using the manual installation

@CypherpunkSamurai would you like to add the required dependencies for your installation script on the README ?

**Comment by luni3359** [comment]
Sorry, I should have mentioned that it wasn't an error-error. It is on the README already, I just wasn't expecting there to be another requirement in the automatic installer.

**Comment by srevinsaju** [comment]
oh nvm, it was already on the README haha, thanks again @CypherpunkSamurai sorry lol
