### ISSUE TITLE
Github based Appimage - Update only necessary Appimage

### ISSUE THREAD

**Issue by vampywiz17** [srevinsaju/zap#49]
Hello there,

Now if i use `zap upgrade` command, it update all appimage, regardless if need, or not. It not possible to add a feature, that only update the Appimage that really changed?

**Comment by srevinsaju** [comment]
Yes, #48 attempts to improve that, will be in a new Zap release really soon!

**Comment by srevinsaju** [comment]
The latest 'continuous' release featuring @ratogabriel 's work should fix that issue! Feel free to open a new issue if the issue still perisists.
