### ISSUE TITLE
Installs 404-html file, when file is missing

### ISSUE THREAD

**Issue by owzim** [srevinsaju/zap#54]
It should fail and not download and `install` the 404 response html

![image](https://user-images.githubusercontent.com/1720088/146732713-ea53db40-f49c-4eed-b97b-563d9f4e8b78.png)

Also: why is the file missing and still listed.

**Comment by Eeems** [comment]
I'm also encountering this

**Comment by srevinsaju** [comment]
Yes! good catch, I will work on it. Its certainly a bug.

**Comment by srevinsaju** [comment]
Fixed this on master, will work on a release now. 

> Also: why is the file missing and still listed.
@owzim this is because the releases are cached using github actions on [`get-appimage`](https://github.com/srevinsaju/get-appimage) repository, which runs approximately every day

**Comment by srevinsaju** [comment]
As a temporary workaround, until this is fixed on `get-appimage`, the command should be 
```bash
zap install --github --from=srevinsaju/Firefox-AppImage firefox
```

**Comment by srevinsaju** [comment]
Done, this is fixed now.

**Comment by srevinsaju** [comment]
Feel free to reopen, or create a new issue, if this issue persists.
