### ISSUE TITLE
zap installation should ask for `$PATH` addition

### ISSUE THREAD

**Issue by owzim** [srevinsaju/zap#57]
Or at least check, if the path is already In `$PATH` and then skip this step.

![image](https://user-images.githubusercontent.com/1720088/147923551-a780d87b-083b-48ed-a9b7-8bb00eca53d0.png)

**Comment by srevinsaju** [comment]
Yes, thats an important bug. I have added a commit here which fixes it 

https://github.com/srevinsaju/zap/commit/a7365d2a5ccb5af78a3da8b1a04ca865344ceb77

Let me know if you still face the issue :sparkles:
