### ISSUE TITLE
Provide zap as .AppImage

### ISSUE THREAD

**Issue by Semnodime** [srevinsaju/zap#61]

**Comment by srevinsaju** [comment]
@Semnodime What would be the use case for providing zap as an appimage?

**Comment by Semnodime** [comment]
Installation with no dependencies regarding curl, grep jq and wget

**Comment by srevinsaju** [comment]
I see, you can still use `zap` without any of the dependencies, 
1. Navigate to https://github.com/srevinsaju/zap/releases/tag/continuous and download the zap binary for your respective architecture 
2. Drag and drop them in `~/.local/bin`
3. Give it execute permissions, by right click and allow exection check box in file manager
4. Use `zap` as normal
