### ISSUE TITLE
Not saved option: Do you want to integrate AppImages by default?

### ISSUE THREAD

**Issue by misog** [srevinsaju/zap#65]
Hi, nice package! I want to configure zap to ask for AppImages integration. When I run `zap init` and answer `ask` to question `Do you want to integrate AppImages by default?` then it has no effect when installing firefox_esr, no asking. `firefox_esr.desktop` file is created, so integration works.

When I run `zap init` again then `yes` is selected again.

OS: PureOS 10 (Debian based)
zap installed without sudo

**Comment by srevinsaju** [comment]
Ah, right! I just realized that I forgot to implement the ask part of it. Thanks for raising this issue!
