### ISSUE TITLE
How to uninstall the application

### ISSUE THREAD

**Issue by YahiaJr** [srevinsaju/zap#71]
I used the installation method mentioned in repo's home page.

How can I uninstall it first from the system?

**Comment by srevinsaju** [comment]
To uninstall a specific app, 
```bash
zap uninstall <appname>
```

After uninstalling all apps from zap
```bash
rm -rf ~/.local/share/zap
rm -rf ~/.config/zap
rm -rf ~/.local/bin/zap
```

We do not have an uninstall script or uninstall command right now, but the above commands should work.

**Comment by ZevSwe** [comment]
The package is installed in /usr/local/bin/ so you would need to run 'sudo rm -rf /usr/local/bin/zap' as well if you installed it globally.
