### ISSUE TITLE
bottles: this app does not provide any candidate for installation

### ISSUE THREAD

**Issue by cmdrneon** [srevinsaju/zap#72]
I'm trying to install Bottles via Zap as a possible alternative to Flatpak. 

I don't prefer how Flatpak keeps everything in a sandbox as it makes it much harder to manage everything for me, and disk usage is much higher than using standard system libraries. Zap being closest to a user-level non-sandboxed package manager makes it easier for me in general.

However, whenever I put in the command
`zap install bottles`
as it tells me to both after `search`ing the package with Zap, or on the official Bottles website, I get the error
`[FATAL] 2022/04/04 16:22:28 main.main:main.go:163 this app does not provide any candidate for installation`

Is there something I'm doing wrong with Zap? 

Thanks in advance.

**Comment by srevinsaju** [comment]
@cmdrneon maybe this issue is related https://github.com/bottlesdevs/Bottles/issues/1272
