### ISSUE TITLE
Propose using absoulute path for the Exec key in desktop entry

### ISSUE THREAD

**Issue by JuanCldCmt** [srevinsaju/zap#78]
Hello, dev:
I've just noticed that, if using local installation mode, the desktop entry does not show up in my desktop environment.
After some research I [found](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables) that if the program is not in the **window manager's ```$PATH```**, the entry will be ignored:
 > If no full path is provided the executable is looked up in the $PATH environment variable used by the desktop environment. 

And in the .desktop file zap installs (in my case it's obsidian, but also true for any other program) :
```
Exec=obsidian-releases %U
```
To enhance compatibility in case the window manager does not know ```~/.local/bin``` or can't change ```$PATH``` variables, I suggest changing the default Exec key to point to the absolute path where the program is installed (like the one in TryExec key):
```
Exec=/home/<username>/.local/bin/obsidian-releases %U
TryExec=/home/<username>/.local/bin/obsidian-releases
```
This can potentially fix other problems, like if you have software that is installed through package manager, using absolute path will always ensure that you are actually launching the appimage version.

**Comment by srevinsaju** [comment]
@JuanCldCmt Thanks for the issue. I have implemented the same in https://github.com/srevinsaju/zap/commit/63fa149a06584b07b1d485a76febe939d78e2e1c
