### ISSUE TITLE
zap init enabling auto updates bug

### ISSUE THREAD

**Issue by fammu03** [srevinsaju/zap#89]
`zap init` reveals a bunch of configurations that can be changed
upon enabling auto updates, it throws the following error
```
? Do you want to enable auto-update? Yes
2022/10/06 20:58:15 Probably not launched by systemd (please file an issue if this is wrong)
2022/10/06 20:58:15 /etc/systemd/user/zapd.service does not exist
2022/10/06 20:58:15 Creating ~/.config/systemd/user/zapd.service
[INFO]  2022/10/06 20:58:15 Restarting via systemd...
```
and proceeds to not display the other settings.

The above problem occurs **only** when enabling it. Disabling it lets it take its normal course.

![image](https://user-images.githubusercontent.com/77967904/194356296-ab784789-6df8-4338-a117-cc6b27aa0295.png)

**Comment by srevinsaju** [comment]
Fixed by #97
