### ISSUE TITLE
AppImage Icons Missing from Zap System Integration

### ISSUE THREAD

**Issue by kj4ezj** [srevinsaju/zap#92]
When you install AppImages using `zap` in Linux Mint 20.3 Cinnamon with system integration, the icons in the start menu and on the taskbar are missing.

## Example 1 - Bitwarden
Steps to reproduce the issue.
1. Download the [Bitwarden](https://bitwarden.com) `*.AppImage` to `~/Downloads/Bitwarden.AppImage`.
   ```bash
   curl -fSL 'https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage' -o ~/Downloads/Bitwarden.AppImage
   ```
2. Use `zap` to install Bitwarden.
   ```bash
   zap install bitwarden ~/Downloads/Bitwarden.AppImage
   ```
3. Proceed with installation when asked `Downloading bitwarden of size (unknown).`.
   `[Y]`, `[Enter]`
4. Approve system integration when prompted `? Do you want to integrate this appimage? [? for help] (y/N)`.
   `[Y]`, `[Enter]`

The Bitwarden logo, present in the `*.AppImage`, is missing from the start menu entry and the task bar icon.

![2022-10-07 15-20-07 - Bitwarden logo missing after zap installation](https://user-images.githubusercontent.com/34947245/194638677-d6cb379f-fd27-4d76-8cf7-6fd940657d12.png)

Note the contents of `~/.local/share/applications/bitwarden.desktop`.
```
[Desktop Entry]
Name=Bitwarden (AppImage)
Exec=bitwarden %U
Terminal=false
Type=Application
Icon=bitwarden
StartupWMClass=Bitwarden
X-AppImage-Version=2022.9.1
GenericName=Password Manager
Comment=A secure and free password manager for all of your devices.
MimeType=x-scheme-handler/bitwarden;
Categories=Utility;
X-AppImage-Integrate=
X-Zap-Id=bitwarden
TryExec=/home/$USER/.local/bin/bitwarden
```
The file at `/home/$USER/.local/bin/bitwarden` is a symbolic link pointing to the binary `/home/$USER/.local/share/zap/v2/bitwarden`. Here, in the `v2` folder, you will find an `icons` subfolder containing `bitwarden.png`, the `*.AppImage` icon.

You can fix the missing icons by giving `Icon` in `bitwarden.desktop` the path to this file. Be sure to replace `$USER` with your username.
```bash
sed -E 's_(Icon=).*$_\1/home/$USER/.local/share/zap/v2/icons/bitwarden.png_' -i ~/.local/share/applications/bitwarden.desktop
```
This provides the logo `zap` already has to the GUI integration.

![2022-10-07 16-15-20 - Bitwarden with logo restored](https://user-images.githubusercontent.com/34947245/194646885-217b9820-4682-4cca-b1ca-a760e7478824.png)

## Example 2 - Joplin
Here again, when you install [Joplin](https://joplinapp.org) using `zap`, the icon present in the `*.AppImage` file is saved by `zap` but missing from the system integration.
```bash
zap install --from 'https://github.com/laurent22/joplin/releases/download/v2.8.8/Joplin-2.8.8.AppImage' joplin
```
It can be restored by pointing the `Icon` field in the `joplin.desktop` file to the icon `zap` saved. Be sure to replace `$USER` with your username.
```bash
sed -E 's_(Icon=).*$_\1/home/$USER/.local/share/zap/v2/icons/joplin.png_' -i ~/.local/share/applications/joplin.desktop
```
This fixes the issue.

## System
System
```
Kernel: 5.4.0-126-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
base: Ubuntu 20.04 focal
```
Zap
```
$ zap --version
Zap version Build:v2.2.1.6.gdc5b7ff 1646814234
```

**Comment by srevinsaju** [comment]
Thanks for the detailed issue description. Can you try using `zap init` and enabling custom icons? (this is just for debugging, if it works with custom icons).

**Comment by kj4ezj** [comment]
Hey, sorry for being so slow to respond. I didn't get a notification for your reply for some reason.

I tried what you suggested using [Joplin](joplinapp.org), since it preserves your local data when you uninstall it. I was using the same version of Joplin (`v2.8.8`) and Zap (`Zap version Build:v2.2.1.6.gdc5b7ff 1646814234`) as when I opened the issue. Here is what I tried.

![2022-10-31 12-52-28 - zap install joplin after init command](https://user-images.githubusercontent.com/34947245/199067143-eeb9e08e-2597-49e6-a2c3-ec45b3162366.png)

Unfortunately, the same problem persists.

![2022-10-31 12-54-32 - Joplin icon missing after zap init and install](https://user-images.githubusercontent.com/34947245/199067195-2541a640-d1fa-4288-8eb6-f39215553cda.png)

Please let me know how I can continue to help troubleshoot, and hopefully the notifications work this time around.
